var digraph = require('./digraph');
var attribute = require('./attribute');
var g = digraph();
g.add.node(1,'a',50,50,1,'red', 'GroupA',new attribute('key', 'value'));
g.add.node(2,'b',50,50,1,'red', 'GroupB',new attribute('key', 'value'));
g.add.node(3,'c',50,50,1,'red', 'GroupB',new attribute('key', 'value'));
g.add.edge(100,'a','b');
g.add.edge(101,'a','c','LABEL');
g.add.edge(102,'a','d');
console.log(g.get.nodes());
console.log(g.get.edges());
console.log(g.get.out.edges('a'));
console.log(g.get.in.edges('c'));
console.log(g.indexof('d'));
console.log(g.getAttr('a'));
console.log(g.export.obj());
console.log(g.export.dot());